name:                shake-ui
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saurabhnanda/shake-ui#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           Saurabh Nanda
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  shake-ui:
    source-dirs:      src
    main:             Main.hs
