name:                shake-ui
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saurabhnanda/shake-ui#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           Saurabh Nanda
category:            Web
extra-source-files:
- README.md

default-extensions:
  - LambdaCase
  - RecordWildCards
  - NamedFieldPuns
  - TypeFamilies
  - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - time
  - directory
  - process
  - typed-process
  - microlens
  - mtl
  - friendly-time
  - either
  - split
  - safe
  - unliftio
  - filepath
  - temporary
  - string-conv
  - unix
  - brick
  - vty
  - fsnotify
  - shake

library:
  source-dirs:      src
  exposed-modules:
    - Development.Shake.UI
    - Development.Shake.UI.Types
  ghc-options:
    - -Wall
    - -fno-warn-orphans
    - -fno-warn-unused-imports
    - -fno-warn-dodgy-exports
    - -Werror=missing-fields
    - -Werror=incomplete-patterns
    - -O0


